project:
  type: website

website:
  title: "Sirius Blog"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - href: Mathematical-Foundations-of-Machine-Learning/index.qmd
        text: Mathematics
      - href: about.qmd
        text: About

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true
