project:
  type: website

website:
  title: "Sirius Blog"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - href: Mathematical-Foundations-of-Machine-Learning/index.qmd
        text: Mathematics
      - href: about.md
        text: About

format:
  html:
    theme: cosmo
    toc: true
